### ISSUE TITLE
Error on Pay Now

### ISSUE THREAD

**Issue by dheerajgupta28** [andrew-grischenko/BraintreePaymentsPCF#4]
I have set up the checkout url for the Braintree component. Facing error on Pay Now button with error "There's been an error processing payment. TypeError: Failed to fetch". Can you pl suggest what can be the issue?

**Comment by andrew-grischenko** [comment]
Hi @dheerajgupta28 
Did you set up the Azure Function as described on the readme in the section [Setup Azure function](https://github.com/andrew-grischenko/BraintreePaymentsPCF#setup-checkout-azure-function) ?
 Where is the error exactly? Can you see some details in the browser console?
Please give me more details so I may help to troubleshoot.

**Comment by dheerajgupta28** [comment]
Yes we setup the Azure function as described. Earlier to this we got the issue "There was a problem importing tk_braintreepaymentsdemo_6ed4a_DocumentUri. A 'ServerException' occurred on the server, activityId 61a7d73d-0738-4b01-b20e-ce615ed65937" while import the component. This was resolved after replacing 'tema' prefix with 'tk' in one of the files.  
After that we got this error finally. We were using Canvas app.
I do not have the screen shots or any other details available now as we deleted Canvas app and trying now with Powerapps Portal. Here we are facing issue after payment processing while redirecting back to receipt page. Attached the screen error details.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/64770524/109647322-28c51600-7b7f-11eb-918b-2c4cb39bdda5.png)

**Comment by andrew-grischenko** [comment]
I suggest you try to change settings in the CORS section of your azure function, the error seems stemming from there. Screenshot is just from another function, but try to enable the cORS credentials or add “*” as a source 
<img width="990" alt="Cora" src="https://user-images.githubusercontent.com/17406795/109648425-b5d39380-7bae-11eb-8edf-572e78957509.png">

**Comment by dheerajgupta28** [comment]
Tried enabling this but no luck. Same error.

**Comment by andrew-grischenko** [comment]
OK, it seems PowerApps Portal then. 
Check out this thread https://powerusers.microsoft.com/t5/Power-Apps-Portals/CORS-setting-in-powerportal/td-p/381053 and here is the link  to how to configure: https://docs.microsoft.com/en-us/dynamics365/marketing/developer/portal-hosted#configuring-cross-origin-resource-sharing-cors 
Let me know please if it helped.

**Comment by dheerajgupta28** [comment]
Thanks for sharing. We tried this but still the same issue.

**Comment by dheerajgupta28** [comment]
The CORS problem seems sorted as of now but we are not able to get the receipt page. The transaction gets stuck at payment processing page. Can you pl suggest how to check if the Azure Function is executing properly?

**Comment by andrew-grischenko** [comment]
Dheeraj,
It's a bit difficult to advise without knowing additional details. 

- Are you implementing a solution similar to what I describe here https://technomancy.com.au/2019/08/12/payments-in-powerapps-portal-part-1-2/ ? 
- What do you mean by the "The transaction gets stuck at payment processing page"? Do you mean it doesn't redirect to the receipts page? 
- If so, does your client browser script get a response from the Azure Function or not? You may want to check the Networks log in the browser.  
- Azure Function - have you put correct URLs, client/secret keys?
- Can you see any messages in the "Log" window in Azure Portal? Is it getting invoked? Does it provide a response?

If neither of these tips helps, I'm happy to jump on a 30 min call to help you troubleshoot, but I'm in Australia (UTC+10). My email is andrew@technomancy.com.au.

**Comment by dheerajgupta28** [comment]
Hi Andrew,

I missed to connect you today. I know it is weekend tomorrow but still if
you are available tomorrow on Saturday pl let me know the time or when you
can be available to connect for screen share session. I will share invite
on MT. I am in India time zone.

Appreciate your help. Thank you.


Regards,
Dheeraj

**Comment by andrew-grischenko** [comment]
Sorry, too busy weekend! I'm available weekday 8 pm Sydney time (+10 UTC) - drop me a Teams meeting to that email. Talk soon!

**Comment by dheerajgupta28** [comment]
Sure and Thank You. I have sent you the meeting invite. Lets connect at 8p
Sydney time (2:30p IST).

https://teams.microsoft.com/l/meetup-join/19%3ameeting_OWU3NGMzMzktM2VlMy00MmRjLWJjMjYtMDcwMGVkZjBjODdm%40thread.v2/0?context=%7b%22Tid%22%3a%22c267ab5c-1d46-4727-94a1-f9eeb396d530%22%2c%22Oid%22%3a%22e79d6819-5b5d-4c95-9dd3-eb991c2ed4dd%22%7d

Regards,
Dheeraj

**Comment by andrew-grischenko** [comment]
Can you also try this?
https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/entity-forms#request-validation

**Comment by dheerajgupta28** [comment]
We have tried this but no luck.

Regards,
Dheeraj

**Comment by dheerajgupta28** [comment]
Hi Andrew,

We replicated the site and tried again. It worked this time. The
transaction was able to redirect to receipt page showing the payment
reference no and amount.
Though not sure what was causing the issue but this is resolved for now.
Thanks


Regards,
Dheeraj

**Comment by andrew-grischenko** [comment]
I'm really glad this has been resolved!
